# Generated by Django 4.1.1 on 2022-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
                ('last_modified_time', models.DateTimeField()),
                ('id_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
    ]
